// ─── Mock Data for CleanConnect+ — Coimbatore ──────────────────────────────

export const COMPLAINTS = [
  {
    id: 'CC-2025-001',
    title: 'Overflowing Garbage Bin',
    description: 'The garbage bin on DB Road near the RS Puram roundabout has been overflowing for 3 days. Waste is spilling onto the footpath and causing hygiene issues.',
    category: 'Overflowing Bin',
    categoryIcon: 'trash-can-outline',
    status: 'In Progress',
    location: 'DB Road, RS Puram, Zone A',
    area: 'RS Puram & Saibaba Colony',
    date: '2025-07-28',
    time: '09:30 AM',
    image: null,
    assignedDriver: 'Murugan S',
    assignedVehicle: 'TN-38-AA-1234',
    latitude: 11.0073,
    longitude: 76.9617,
    resolutionNotes: 'Driver dispatched. Expected collection by 2 PM.',
    timeline: [
      { status: 'Submitted', time: '09:30 AM, 28 Jul', note: 'Complaint registered successfully.' },
      { status: 'Reviewing', time: '10:00 AM, 28 Jul', note: 'Complaint verified by supervisor.' },
      { status: 'In Progress', time: '11:30 AM, 28 Jul', note: 'Driver Murugan assigned to the location.' },
    ],
  },
  {
    id: 'CC-2025-002',
    title: 'Illegal Waste Dumping',
    description: 'Someone has been illegally dumping construction debris near Singanallur Lake. This needs immediate attention.',
    category: 'Illegal Dumping',
    categoryIcon: 'alert-circle-outline',
    status: 'Pending',
    location: 'Singanallur Lake Road, Zone D',
    area: 'Singanallur & Hopes College',
    date: '2025-07-27',
    time: '02:15 PM',
    image: null,
    assignedDriver: null,
    assignedVehicle: null,
    latitude: 10.9967,
    longitude: 77.0151,
    resolutionNotes: null,
    timeline: [
      { status: 'Submitted', time: '02:15 PM, 27 Jul', note: 'Complaint registered successfully.' },
    ],
  },
  {
    id: 'CC-2025-003',
    title: 'Missed Collection',
    description: 'Garbage truck missed our street in Saibaba Colony for the second consecutive week.',
    category: 'Missed Collection',
    categoryIcon: 'truck-remove-outline',
    status: 'Completed',
    location: 'Saibaba Colony Main Road, Zone A',
    area: 'RS Puram & Saibaba Colony',
    date: '2025-07-20',
    time: '08:00 AM',
    image: null,
    assignedDriver: 'Selvam K',
    assignedVehicle: 'TN-38-AB-5678',
    latitude: 11.0112,
    longitude: 76.9572,
    resolutionNotes: 'Collection completed. Route has been updated to include this street.',
    timeline: [
      { status: 'Submitted', time: '08:00 AM, 20 Jul', note: 'Complaint registered.' },
      { status: 'Reviewing', time: '09:00 AM, 20 Jul', note: 'Under review.' },
      { status: 'In Progress', time: '10:00 AM, 20 Jul', note: 'Driver dispatched.' },
      { status: 'Completed', time: '01:00 PM, 20 Jul', note: 'Collection done. Route updated.' },
    ],
  },
  {
    id: 'CC-2025-004',
    title: 'Broken Bin',
    description: 'The public bin near Gandhipuram bus stop has a broken lid and is attracting stray animals.',
    category: 'Damaged Infrastructure',
    categoryIcon: 'wrench-outline',
    status: 'Pending',
    location: 'Gandhipuram Bus Stand, Zone B',
    area: 'Gandhipuram & Race Course',
    date: '2025-07-29',
    time: '11:45 AM',
    image: null,
    assignedDriver: null,
    assignedVehicle: null,
    latitude: 11.0168,
    longitude: 76.9558,
    resolutionNotes: null,
    timeline: [
      { status: 'Submitted', time: '11:45 AM, 29 Jul', note: 'Complaint registered.' },
    ],
  },
];

export const NOTIFICATIONS = [
  {
    id: 'N001',
    title: 'Garbage Collection Tomorrow',
    message: 'Your area (RS Puram & Saibaba Colony) is scheduled for garbage collection tomorrow at 7:00 AM.',
    type: 'schedule',
    icon: 'calendar-check',
    time: '2 hours ago',
    isRead: false,
    color: '#2E7D32',
  },
  {
    id: 'N002',
    title: 'Complaint Updated',
    message: 'Your complaint CC-2025-001 has been assigned to driver Murugan S. Expected resolution by 2:00 PM.',
    type: 'complaint',
    icon: 'clipboard-check-outline',
    time: '3 hours ago',
    isRead: false,
    color: '#1565C0',
  },
  {
    id: 'N003',
    title: 'Truck Nearby',
    message: 'Your garbage collection truck is approximately 500 metres away. Please keep your bin ready.',
    type: 'tracking',
    icon: 'truck-fast',
    time: '5 hours ago',
    isRead: true,
    color: '#FFC107',
  },
  {
    id: 'N004',
    title: 'Complaint Resolved',
    message: 'Your complaint CC-2025-003 has been successfully resolved. Thank you for helping us keep Coimbatore clean.',
    type: 'complaint',
    icon: 'check-circle-outline',
    time: '2 days ago',
    isRead: true,
    color: '#4CAF50',
  },
  {
    id: 'N005',
    title: 'New Collection Schedule',
    message: 'Your collection schedule has been updated. Zone A (RS Puram) will now be collected every Monday and Thursday.',
    type: 'schedule',
    icon: 'bell-outline',
    time: '3 days ago',
    isRead: true,
    color: '#2E7D32',
  },
];

export const SCHEDULE = [
  {
    id: 'S001',
    day: 'Monday',
    date: '2025-07-28',
    area: 'RS Puram & Saibaba Colony',
    time: '7:00 AM - 10:00 AM',
    type: 'General Waste',
    icon: 'trash-can',
    color: '#2E7D32',
    driver: 'Murugan S',
    vehicle: 'TN-38-AA-1234',
    status: 'Completed',
  },
  {
    id: 'S002',
    day: 'Wednesday',
    date: '2025-07-30',
    area: 'RS Puram & Saibaba Colony',
    time: '8:00 AM - 11:00 AM',
    type: 'Recyclables',
    icon: 'recycle',
    color: '#1565C0',
    driver: 'Selvam K',
    vehicle: 'TN-38-AB-5678',
    status: 'Upcoming',
  },
  {
    id: 'S003',
    day: 'Thursday',
    date: '2025-07-31',
    area: 'RS Puram & Saibaba Colony',
    time: '7:00 AM - 10:00 AM',
    type: 'General Waste',
    icon: 'trash-can',
    color: '#2E7D32',
    driver: 'Murugan S',
    vehicle: 'TN-38-AA-1234',
    status: 'Today',
  },
  {
    id: 'S004',
    day: 'Saturday',
    date: '2025-08-02',
    area: 'RS Puram & Saibaba Colony',
    time: '9:00 AM - 12:00 PM',
    type: 'Organic Waste',
    icon: 'leaf',
    color: '#4CAF50',
    driver: 'Arun R',
    vehicle: 'TN-38-AC-9012',
    status: 'Upcoming',
  },
];

export const DRIVER_ROUTES = [
  {
    id: 'R001',
    stopNumber: 1,
    address: '12, DB Road, RS Puram',
    area: 'Zone A',
    landmark: 'Near RS Puram Roundabout',
    distance: '0.0 km',
    eta: '7:15 AM',
    status: 'Completed',
    complaintsCount: 2,
    latitude: 11.0073,
    longitude: 76.9617,
  },
  {
    id: 'R002',
    stopNumber: 2,
    address: '45, Bharathi Park Road, Saibaba Colony',
    area: 'Zone A',
    landmark: 'Opposite Saibaba Colony Park',
    distance: '0.8 km',
    eta: '7:35 AM',
    status: 'In Progress',
    complaintsCount: 0,
    latitude: 11.0112,
    longitude: 76.9572,
  },
  {
    id: 'R003',
    stopNumber: 3,
    address: '78, Race Course Road, Gandhipuram',
    area: 'Zone B',
    landmark: 'Near Race Course',
    distance: '1.5 km',
    eta: '7:55 AM',
    status: 'Pending',
    complaintsCount: 1,
    latitude: 11.0168,
    longitude: 76.9558,
  },
  {
    id: 'R004',
    stopNumber: 4,
    address: '23, Avinashi Road, Peelamedu',
    area: 'Zone C',
    landmark: 'Near Peelamedu Signal',
    distance: '2.3 km',
    eta: '8:20 AM',
    status: 'Pending',
    complaintsCount: 0,
    latitude: 11.0268,
    longitude: 77.0007,
  },
  {
    id: 'R005',
    stopNumber: 5,
    address: '56, Trichy Road, Singanallur',
    area: 'Zone D',
    landmark: 'Singanallur Bus Stop',
    distance: '3.1 km',
    eta: '8:45 AM',
    status: 'Pending',
    complaintsCount: 3,
    latitude: 10.9967,
    longitude: 77.0151,
  },
];

export const DRIVER_STATS = {
  today: {
    completed: 8,
    remaining: 5,
    totalStops: 13,
    complaintsResolved: 3,
    distanceCovered: '12.4 km',
    workHours: '3h 20m',
  },
};

export const CATEGORIES = [
  { label: 'Overflowing Bin', value: 'overflow', icon: 'trash-can-outline' },
  { label: 'Missed Collection', value: 'missed', icon: 'truck-remove-outline' },
  { label: 'Illegal Dumping', value: 'illegal', icon: 'alert-circle-outline' },
  { label: 'Damaged Infrastructure', value: 'damaged', icon: 'wrench-outline' },
  { label: 'Foul Odor', value: 'odor', icon: 'weather-windy' },
  { label: 'Stray Animals', value: 'animals', icon: 'dog' },
  { label: 'Other', value: 'other', icon: 'help-circle-outline' },
];

export const QUICK_ACTIONS = [
  { id: 'qa1', title: 'Report\nIssue', icon: 'alert-circle-outline', color: '#E53935', bg: '#FFEBEE', route: 'ReportComplaint' },
  { id: 'qa2', title: 'Track\nTruck', icon: 'truck-fast', color: '#1565C0', bg: '#E3F2FD', route: 'LiveTracking' },
  { id: 'qa3', title: 'Collection\nSchedule', icon: 'calendar-month', color: '#2E7D32', bg: '#E8F5E9', route: 'CollectionSchedule' },
  { id: 'qa4', title: 'My\nComplaints', icon: 'clipboard-list-outline', color: '#FF8F00', bg: '#FFF8E1', route: 'ComplaintHistory' },
];

export const TRUCK_INFO = {
  id: 'GCT-001',
  plateNumber: 'TN-38-AA-1234',
  driver: 'Murugan S',
  driverPhone: '+91 94876 54321',
  vehicleType: 'Compactor Truck',
  capacity: '5 Tonnes',
  currentLocation: 'Race Course Road, Gandhipuram',
  eta: '15 min',
  distance: '1.2 km',
  status: 'On Route',
  lastUpdated: '2 min ago',
  latitude: 11.0168,
  longitude: 76.9558,
};

export const CITIZEN_PROFILE = {
  name: 'Aravind Kumar',
  email: 'aravind.kumar@email.com',
  phone: '+91 94876 54321',
  area: 'Zone A - RS Puram',
  address: '12, DB Road, RS Puram, Coimbatore - 641002',
  memberSince: 'January 2024',
  complaintsRaised: 12,
  complaintsResolved: 9,
  avatar: null,
};

export const DRIVER_PROFILE = {
  name: 'Murugan S',
  employeeId: 'EMP-2024-056',
  email: 'murugan.s@cleanconnect.gov.in',
  phone: '+91 87654 32109',
  zone: 'Zone A & B',
  vehicle: 'TN-38-AA-1234',
  vehicleType: 'Compactor Truck',
  shift: '6:00 AM - 2:00 PM',
  joiningDate: 'March 2022',
  totalCollections: 1247,
  rating: 4.8,
  avatar: null,
};
