// ─── Mock Data for CleanConnect+ ────────────────────────────────────────────

export const COMPLAINTS = [
  {
    id: 'CC-2025-001',
    title: 'Overflowing Garbage Bin',
    description: 'The garbage bin on Main Street near the park has been overflowing for 3 days. Waste is spilling onto the sidewalk and causing hygiene issues.',
    category: 'Overflowing Bin',
    categoryIcon: 'trash-can-outline',
    status: 'In Progress',
    location: 'Main Street, Near Central Park, Zone A',
    area: 'Zone A - Central District',
    date: '2025-07-28',
    time: '09:30 AM',
    image: null,
    assignedDriver: 'Rajesh Kumar',
    assignedVehicle: 'TN-01-AB-1234',
    latitude: 13.0827,
    longitude: 80.2707,
    resolutionNotes: 'Driver dispatched. Expected collection by 2 PM.',
    timeline: [
      { status: 'Submitted', time: '09:30 AM, 28 Jul', note: 'Complaint registered successfully.' },
      { status: 'Reviewing', time: '10:00 AM, 28 Jul', note: 'Complaint verified by supervisor.' },
      { status: 'In Progress', time: '11:30 AM, 28 Jul', note: 'Driver Rajesh assigned to the location.' },
    ],
  },
  {
    id: 'CC-2025-002',
    title: 'Illegal Waste Dumping',
    description: 'Someone has been illegally dumping construction debris near the lake. This needs immediate attention.',
    category: 'Illegal Dumping',
    categoryIcon: 'alert-circle-outline',
    status: 'Pending',
    location: 'Lake View Road, Zone B',
    area: 'Zone B - Lake District',
    date: '2025-07-27',
    time: '02:15 PM',
    image: null,
    assignedDriver: null,
    assignedVehicle: null,
    latitude: 13.09,
    longitude: 80.28,
    resolutionNotes: null,
    timeline: [
      { status: 'Submitted', time: '02:15 PM, 27 Jul', note: 'Complaint registered successfully.' },
    ],
  },
  {
    id: 'CC-2025-003',
    title: 'Missed Collection',
    description: 'Garbage truck missed our street for the second consecutive week.',
    category: 'Missed Collection',
    categoryIcon: 'truck-remove-outline',
    status: 'Completed',
    location: 'Rose Garden Street, Zone C',
    area: 'Zone C - Garden District',
    date: '2025-07-20',
    time: '08:00 AM',
    image: null,
    assignedDriver: 'Suresh Patel',
    assignedVehicle: 'TN-01-CD-5678',
    latitude: 13.07,
    longitude: 80.26,
    resolutionNotes: 'Collection completed. Route has been updated to include this street.',
    timeline: [
      { status: 'Submitted', time: '08:00 AM, 20 Jul', note: 'Complaint registered.' },
      { status: 'Reviewing', time: '09:00 AM, 20 Jul', note: 'Under review.' },
      { status: 'In Progress', time: '10:00 AM, 20 Jul', note: 'Driver dispatched.' },
      { status: 'Completed', time: '01:00 PM, 20 Jul', note: 'Collection done. Route updated.' },
    ],
  },
  {
    id: 'CC-2025-004',
    title: 'Broken Bin',
    description: 'The public bin near the bus stop has a broken lid and is attracting stray animals.',
    category: 'Damaged Infrastructure',
    categoryIcon: 'wrench-outline',
    status: 'Pending',
    location: 'Bus Stop 14, Zone A',
    area: 'Zone A - Central District',
    date: '2025-07-29',
    time: '11:45 AM',
    image: null,
    assignedDriver: null,
    assignedVehicle: null,
    latitude: 13.085,
    longitude: 80.271,
    resolutionNotes: null,
    timeline: [
      { status: 'Submitted', time: '11:45 AM, 29 Jul', note: 'Complaint registered.' },
    ],
  },
];

export const NOTIFICATIONS = [
  {
    id: 'N001',
    title: 'Garbage Collection Tomorrow',
    message: 'Your area (Zone A - Central District) is scheduled for garbage collection tomorrow at 7:00 AM.',
    type: 'schedule',
    icon: 'calendar-check',
    time: '2 hours ago',
    isRead: false,
    color: '#2E7D32',
  },
  {
    id: 'N002',
    title: 'Complaint Updated',
    message: 'Your complaint CC-2025-001 has been assigned to driver Rajesh Kumar. Expected resolution by 2:00 PM.',
    type: 'complaint',
    icon: 'clipboard-check-outline',
    time: '3 hours ago',
    isRead: false,
    color: '#1565C0',
  },
  {
    id: 'N003',
    title: 'Truck Nearby',
    message: 'Your garbage collection truck is approximately 500 meters away. Please keep your bin ready.',
    type: 'tracking',
    icon: 'truck-fast',
    time: '5 hours ago',
    isRead: true,
    color: '#FFC107',
  },
  {
    id: 'N004',
    title: 'Complaint Resolved',
    message: 'Your complaint CC-2025-003 has been successfully resolved. Thank you for helping us keep the city clean.',
    type: 'complaint',
    icon: 'check-circle-outline',
    time: '2 days ago',
    isRead: true,
    color: '#4CAF50',
  },
  {
    id: 'N005',
    title: 'New Collection Schedule',
    message: 'Your collection schedule has been updated. Zone A will now be collected every Monday and Thursday.',
    type: 'schedule',
    icon: 'bell-outline',
    time: '3 days ago',
    isRead: true,
    color: '#2E7D32',
  },
];

export const SCHEDULE = [
  {
    id: 'S001',
    day: 'Monday',
    date: '2025-07-28',
    area: 'Zone A - Central District',
    time: '7:00 AM - 10:00 AM',
    type: 'General Waste',
    icon: 'trash-can',
    color: '#2E7D32',
    driver: 'Rajesh Kumar',
    vehicle: 'TN-01-AB-1234',
    status: 'Completed',
  },
  {
    id: 'S002',
    day: 'Wednesday',
    date: '2025-07-30',
    area: 'Zone A - Central District',
    time: '8:00 AM - 11:00 AM',
    type: 'Recyclables',
    icon: 'recycle',
    color: '#1565C0',
    driver: 'Suresh Patel',
    vehicle: 'TN-01-CD-5678',
    status: 'Upcoming',
  },
  {
    id: 'S003',
    day: 'Thursday',
    date: '2025-07-31',
    area: 'Zone A - Central District',
    time: '7:00 AM - 10:00 AM',
    type: 'General Waste',
    icon: 'trash-can',
    color: '#2E7D32',
    driver: 'Rajesh Kumar',
    vehicle: 'TN-01-AB-1234',
    status: 'Today',
  },
  {
    id: 'S004',
    day: 'Saturday',
    date: '2025-08-02',
    area: 'Zone A - Central District',
    time: '9:00 AM - 12:00 PM',
    type: 'Organic Waste',
    icon: 'leaf',
    color: '#4CAF50',
    driver: 'Anand Sharma',
    vehicle: 'TN-01-EF-9012',
    status: 'Upcoming',
  },
];

export const DRIVER_ROUTES = [
  {
    id: 'R001',
    stopNumber: 1,
    address: '12, Rose Garden Street, Zone A',
    area: 'Central District',
    landmark: 'Near Central Park',
    distance: '0.0 km',
    eta: '7:15 AM',
    status: 'Completed',
    complaintsCount: 2,
    latitude: 13.0827,
    longitude: 80.2707,
  },
  {
    id: 'R002',
    stopNumber: 2,
    address: '45, MG Road, Zone A',
    area: 'Central District',
    landmark: 'Opposite City Mall',
    distance: '0.8 km',
    eta: '7:35 AM',
    status: 'In Progress',
    complaintsCount: 0,
    latitude: 13.085,
    longitude: 80.272,
  },
  {
    id: 'R003',
    stopNumber: 3,
    address: '78, Anna Nagar 2nd Street, Zone A',
    area: 'North District',
    landmark: 'Near Anna Nagar Tower',
    distance: '1.5 km',
    eta: '7:55 AM',
    status: 'Pending',
    complaintsCount: 1,
    latitude: 13.09,
    longitude: 80.275,
  },
  {
    id: 'R004',
    stopNumber: 4,
    address: '23, Velachery Main Road, Zone B',
    area: 'South District',
    landmark: 'Beside Reliance Fresh',
    distance: '2.3 km',
    eta: '8:20 AM',
    status: 'Pending',
    complaintsCount: 0,
    latitude: 13.07,
    longitude: 80.265,
  },
  {
    id: 'R005',
    stopNumber: 5,
    address: '56, T Nagar, Zone B',
    area: 'West District',
    landmark: 'Pondy Bazaar Junction',
    distance: '3.1 km',
    eta: '8:45 AM',
    status: 'Pending',
    complaintsCount: 3,
    latitude: 13.04,
    longitude: 80.23,
  },
];

export const DRIVER_STATS = {
  today: {
    completed: 8,
    remaining: 5,
    totalStops: 13,
    complaintsResolved: 3,
    distanceCovered: '12.4 km',
    workHours: '3h 20m',
  },
};

export const CATEGORIES = [
  { label: 'Overflowing Bin', value: 'overflow', icon: 'trash-can-outline' },
  { label: 'Missed Collection', value: 'missed', icon: 'truck-remove-outline' },
  { label: 'Illegal Dumping', value: 'illegal', icon: 'alert-circle-outline' },
  { label: 'Damaged Infrastructure', value: 'damaged', icon: 'wrench-outline' },
  { label: 'Foul Odor', value: 'odor', icon: 'weather-windy' },
  { label: 'Stray Animals', value: 'animals', icon: 'dog' },
  { label: 'Other', value: 'other', icon: 'help-circle-outline' },
];

export const QUICK_ACTIONS = [
  { id: 'qa1', title: 'Report\nIssue', icon: 'alert-circle-outline', color: '#E53935', bg: '#FFEBEE', route: 'ReportComplaint' },
  { id: 'qa2', title: 'Track\nTruck', icon: 'truck-fast', color: '#1565C0', bg: '#E3F2FD', route: 'LiveTracking' },
  { id: 'qa3', title: 'Collection\nSchedule', icon: 'calendar-month', color: '#2E7D32', bg: '#E8F5E9', route: 'CollectionSchedule' },
  { id: 'qa4', title: 'My\nComplaints', icon: 'clipboard-list-outline', color: '#FF8F00', bg: '#FFF8E1', route: 'ComplaintHistory' },
];

export const TRUCK_INFO = {
  id: 'GCT-001',
  plateNumber: 'TN-01-AB-1234',
  driver: 'Rajesh Kumar',
  driverPhone: '+91 98765 43210',
  vehicleType: 'Compactor Truck',
  capacity: '5 Tonnes',
  currentLocation: 'MG Road, Zone A',
  eta: '15 min',
  distance: '1.2 km',
  status: 'On Route',
  lastUpdated: '2 min ago',
  latitude: 13.085,
  longitude: 80.272,
};

export const CITIZEN_PROFILE = {
  name: 'Arjun Mehta',
  email: 'arjun.mehta@email.com',
  phone: '+91 98765 43210',
  area: 'Zone A - Central District',
  address: '12, Rose Garden Street, Central District, Chennai - 600001',
  memberSince: 'January 2024',
  complaintsRaised: 12,
  complaintsResolved: 9,
  avatar: null,
};

export const DRIVER_PROFILE = {
  name: 'Rajesh Kumar',
  employeeId: 'EMP-2024-056',
  email: 'rajesh.kumar@cleanconnect.gov.in',
  phone: '+91 87654 32109',
  zone: 'Zone A & B',
  vehicle: 'TN-01-AB-1234',
  vehicleType: 'Compactor Truck',
  shift: '6:00 AM - 2:00 PM',
  joiningDate: 'March 2022',
  totalCollections: 1247,
  rating: 4.8,
  avatar: null,
};
